// ==========================================
// Vibe Coding Baseline Contracts
// ==========================================

// 1. Student Profile (Generated by Creator and stored by Frontend)
export interface StudentProfile {
    id: string; // e.g. "student_1"
    name: string;
    personality: string; // Detailed system prompt generated text
    baseEngagement: number; // 0-100
}

// 2. Classroom / Input (Sent by Frontend to the Orchestrator)
export interface ClassroomContext {
    sessionId: string;
    students: StudentProfile[]; // Active students
    teacherTranscriptChunk: string; // Latest text validated by the PreProcessor
    fullTranscript?: { speaker: string, text: string }[]; // Full previous conversation history
}

// 3. Student State / Output (Returned by Orchestrator to the Frontend)
export interface StudentResponse {
    studentId: string;
    internalThought: string;
    action: 'LISTEN' | 'RAISE_HAND' | 'ANSWER_DIRECTLY' | 'WHISPER' | 'INTERRUPT';
    message: string | null;
    newEngagement: number; // 0-100
    emotion: 'curious' | 'bored' | 'anxious' | 'excited';
}

export interface PreProcessorResponse {
    isProcessed: boolean;
    extractedContext: string | null;
    remainingBuffer: string;
}

export interface OrchestratorResponse {
    responses: StudentResponse[];
}

// PREVIOUS (Legacy / Currently used) Types
// (stored here as well for shared access)
// ==========================================

export type StudentType = 'Fast Learner' | 'ESL Student' | 'Easily Distracted' | 'Deep Thinker' | 'Anxious Achiever' | 'Class Clown';

export interface Student {
    id: string;
    name: string;
    age: number;
    type: StudentType;
    moodScore: number; // 0-100
    raisedHand: boolean;
    learningStatus: string;
    struggles?: string;
    personality?: string;
    prompt?: string;
    condition?: string | null;
    avatar_url?: string;
    created_at?: string;
    currentAction?: 'LISTEN' | 'RAISE_HAND' | 'ANSWER_DIRECTLY' | 'WHISPER' | 'INTERRUPT';
    currentMessage?: string | null;
}

export interface VirtualClass {
    id: string;
    name: string;
    subject: string;
    description: string;
    students: Student[];
}

export interface TranscriptEntry {
    id: string;
    speaker: 'Teacher' | string; // 'Teacher' or student name
    text: string;
    timestamp: string;
    emotion?: 'neutral' | 'happy' | 'confused' | 'bored' | 'engaged';
    // Engagement snapshot injected after each orchestrator tick (silent + speaking students)
    moodSnapshot?: Record<string, number>; // studentName -> moodScore (0-100)
}
